name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running the script file
      run: |
        echo -- Running Tests ---
        sh ./EAApp/scripts/run.sh
    - name: Publish the report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: SpecFlowReport
        path: ./reports
